Feature/datavalidation
BananaPilot/scuola-develhope pull request #30
Opened 2024-04-21 12:43 UTC by fubu901

aggiornamento data validation

2024-04-21 16:54 UTC, BananaPilot requested changes
cambia cio che ti e' stato chiesto -> e smetti di generare codice con l'ai perfavore

2024-04-21 16:54 UTC, BananaPilot commented on pom.xml
questa roba non e' le dipendenze giuste da aggiungere al progetto ti prego togliele

2024-04-21 16:54 UTC, BananaPilot commented on src/main/java/com/teamproject1/scuoledevelhope/classes/coordinator/controller/CoordinatorController.java
> +        }
questa roba qui sopra e' inutile quando mai abbiamo usato binding resoults e Response entity ti prego di mantenere gli standard di scrittura come abbiamo fatto noi e sopratutto di sutilizziare li stessi dto... se vuoi prossima volta che ci sentiamo ti spiego.

2024-04-21 16:54 UTC, BananaPilot commented on src/main/java/com/teamproject1/scuoledevelhope/classes/coordinator/service/CoordinatorService.java
stessa cosa che ti ho scritto prima
tutto qel papiro nel controller non ci deve stare

2024-04-21 16:54 UTC, BananaPilot commented on src/main/java/com/teamproject1/scuoledevelhope/classes/student/Student.java
👍

2024-04-21 16:54 UTC, BananaPilot commented on src/main/java/com/teamproject1/scuoledevelhope/classes/student/controller/StudentController.java
👎 come scritto prima

2024-04-21 16:54 UTC, BananaPilot commented on src/main/java/com/teamproject1/scuoledevelhope/classes/student/service/StudentService.java
se inserisci valid all interno del controller... poi sai gia che i dati che ti sono stai dati sono validi per cui non ti serve mettere la annotaion valid all interno del service ti conviene togliere per code duplication

2024-04-21 16:54 UTC, BananaPilot commented on src/main/java/com/teamproject1/scuoledevelhope/classes/tutor/Tutor.java
👍

2024-04-21 16:54 UTC, BananaPilot commented on src/main/java/com/teamproject1/scuoledevelhope/classes/tutor/controller/TutorController.java
stessa cosa

2024-04-21 16:54 UTC, BananaPilot commented on src/main/java/com/teamproject1/scuoledevelhope/classes/tutor/service/TutorService.java
nelle creazioni sarebbe meglio ritornare un user creato in modo da poter vedere l'user appena creato

2024-04-21 16:54 UTC, BananaPilot commented on src/main/java/com/teamproject1/scuoledevelhope/types/dtos/BaseResponseElement.java
sta roba te la ha generata chat gpt? mi sembra molto strano.... <3

2024-04-21 17:03 UTC, fubu901 commented on src/main/java/com/teamproject1/scuoledevelhope/types/dtos/BaseResponseElement.java
no, questo no, me lo ha proposto intellij per risolvere un problema...

2024-04-21 17:04 UTC, fubu901 commented on src/main/java/com/teamproject1/scuoledevelhope/classes/coordinator/controller/CoordinatorController.java
> +        }
suggerimenti dell'ai...

2024-04-22 10:46 UTC, BananaPilot approved these changes

2024-04-22 10:46 UTC, merged